### ISSUE TITLE
Imdb

### ISSUE THREAD

**Issue by Arthur1967** [Ezra-Hubbard/Ezra-Hubbard.github.io#16]
My user name shows up but my watchlist is not populated using a fire stick 19.4 do you have to pay for Imbd I put another list in it it populated but mine won't

**Comment by umbrellaplug** [comment]
IMDB is actually using user id numbers instead of your actual id. 
Example: https://www.imdb.com/user/ur154206630/watchlist?ref_=nv_usr_wl_all_0
My user id is actually "Bob Maroney", but in the My Accounts module I think I need to put the numbers after "ur" like this 

imdb id: 1542006630

I haven't messed with IMDB too much for making lists, but I don't think it's a paid feature.

**Comment by Arthur1967** [comment]
OK thank you this is what I like about you you get back to people that's why I will always use Ezra have a good day and I will close this or you can

**Comment by Arthur1967** [comment]
I just came across it a couple days ago and I wonder if he kept track of series better than trakt I am enjoying Ezra thank you for your commitment
