### ISSUE TITLE
The subtitle options have been removed?

### ISSUE THREAD

**Issue by mddfe** [Ezra-Hubbard/Ezra-Hubbard.github.io#5]
Hi,

I always enjoyed using the previous original add-on's subtitle options. It could automatically download subtitles via opensubtitles and it had the option to force it to use local subtitles if they were available.

The option seems to be completely removed from the settings.xml of ezra, but I've noticed that the opensubtitle api files are still there. Perhaps they were removed because they mentioned the previous project? If that's the case, the api files should either be removed entirely, or at least amended to remove any mention of the previous add-on. I believe all that needs to be changed is the user agent name.

Ideally the subtitle options can be restored, but maybe I'm the only one that used that feature, since I've seen no mention of its removal anywhere. In any case, thank you for your time.

**Comment by Ezra-Hubbard** [comment]
ah, i forgot to remove the old api file.

in short, opensubtitles didnt want to issue an "old style" user_agent key for ezra because they have moved to a new api. I could have applied for a new api key but it would have a) meant rewriting the entire epi and b) the api is restricted to 100 calls a day which would have been a problem. You can say the app is in dev mode, but thats kinda abusing a free system to some degree.

Ultimately, it came down to was it worth rewriting the entire api (with limited python knowledge) when there are addons such as a4ksubtitles which do the job better and do it system wide. 

I did plan to softlink to the a4k subs repo to make installing them easier but could not get hold of the dev to include their repo addy

**Comment by mddfe** [comment]
Understood, and I appreciate the detailed response. Makes sense and thanks for all of the contributions you have made to keep this great add-on alive!
